apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 3
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: marquesxmateus/hello-go:v7
          envFrom:
            - configMapRef:
                name: goserver-env
          volumeMounts:
            - name: config
              mountPath: "/go/myfamily"

      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"
